on: [push]

name: Code Quality

jobs:
  style:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Configures terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.1
      - name: Check formatting
        run: terraform fmt -check -recursive
